### ISSUE TITLE
Do you have any plans to implement set_accepts_tab() in View?

### ISSUE THREAD

**Issue by pandanoir** [gtk-rs/sourceview#109]
I want set_accepts_tab() to move keyboard focus between Views with the tab key. Now, View have set_accepts_tab() but there is no implementation.

```rust
    let buff = Buffer::new::<gtk::TextTagTable>(None);
    let view = View::new_with_buffer(&buff);
    view.set_accepts_tab(false); // not working!!
```

Is there any plans to implement it?

**Comment by EPashkin** [comment]
It has implementation: https://github.com/gtk-rs/gtk/blob/master/src/auto/text_view.rs#L1473
If this don't works as you think please read documentation about gtk_text_view_set_accepts_tab

**Comment by pandanoir** [comment]
pressing Ctrl+TAB does what I want to do. I didn't understand how it works.
I'm sorry...
