### ISSUE TITLE
Implementation of load_async and save_async?

### ISSUE THREAD

**Issue by brackleian** [gtk-rs/sourceview#125]
The functions `sourceview::FileLoaderExt::load_async` and `sourceview::FileSaverExt::save_async` are yet to be unimplemented, which means `FileLoader` and `FileSaver` objects are of little use. I would like to be able to use them in a project, and would have a go myself though still a relative Rust newb - are there any non-straightforward design issues holding this up, or should I give it a go?

**Comment by GuillaumeGomez** [comment]
You can give it a try. Check first if it can be generated, and if not, take a look at how it's implemented in our crates (gio as a lot of async calls).

**Comment by brackleian** [comment]
OK, I have some working code. Is there a guide somewhere on how to submit it to github?

**Comment by GuillaumeGomez** [comment]
Just open a PR to the repository.

**Comment by sdroege** [comment]
@GuillaumeGomez This can be closed now
