### ISSUE TITLE
Update from sourceview3 to sourceview4

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/sourceview#130]
The latter is still GTK3 based

**Comment by sdroege** [comment]
It exists here already but we should maybe include it here instead of the deprecated sourceview3?

https://crates.io/crates/sourceview4

@BrainBlasted ?

**Comment by john01dav** [comment]
Version 4 of the upstream Gnome library is still based on GTK3 ([source](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/134)):

> GtkSourceView 4.x is also for GTK 3 (but with all the deprecated API removed).

**Comment by BrainBlasted** [comment]
I would be fine with that, @sdroege

**Comment by sdroege** [comment]
I guess this mostly depends then on whether someone wants to actually maintain it as part of the gtk-rs organization :)

**Comment by bilelmoussaoui** [comment]
I'm open to +/- maintain it, does it matter to move it from /World/Rust to gtk-rs?

**Comment by GuillaumeGomez** [comment]
I'm fine with it.

**Comment by alatiera** [comment]
We could also keep maintaining it as is on the gnome gitlab and instead update the sourceview crate on crater, unless there's something in gtk-rs that depends on it.

**Comment by bilelmoussaoui** [comment]
I guess we can close this, I have updated sourceview4 to the latest release few months ago.
