### ISSUE TITLE
Creating a Language

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/sourceview#24]
I'm not seeing any methods for creating a `Language`, so it's currently impossible to use syntax highlighting within a SourceBuffer.

**Comment by EPashkin** [comment]
See http://gtk-rs.org/docs/sourceview/struct.LanguageManager.html

**Comment by EPashkin** [comment]
@GuillaumeGomez this seems can be closed too.

**Comment by GuillaumeGomez** [comment]
Indeed!
