### ISSUE TITLE
SourceView should  Scrollable

### ISSUE THREAD

**Issue by mardiros** [gtk-rs/sourceview#51]
[From the gnome developper doc](https://developer.gnome.org/gtksourceview/stable/GtkSourceView.html) the Source View Object inherits from scrollable.

[The TextView](http://gtk-rs.org/docs/gtk/struct.TextView.html#implements) type implements ScrollableExt, [this is not the case for sourceview::View](http://gtk-rs.org/docs/sourceview/struct.View.html#implements)

**Comment by GuillaumeGomez** [comment]
That's strange because it's listed into the gir file. And the gir generation doesn't show warning about it. Any idea what's wrong @EPashkin?

**Comment by EPashkin** [comment]
It not listed in your config:
```diff
--- a/Gir.toml
+++ b/Gir.toml
@@ -61,6 +61,7 @@ manual = [
     "GLib.Variant",
     "Gtk.PrintContext",
     "Gtk.ScrollStep",
+    "Gtk.Scrollable",
     "Gtk.TextBuffer",
     "Gtk.TextIter",
     "Gtk.TextMark",
```

**Comment by EPashkin** [comment]
@mardiros Thanks for reporting

**Comment by GuillaumeGomez** [comment]
Considering that it's a dependency, shouldn't we at least have a warning about it? It'd be really helpful.

**Comment by mardiros** [comment]
kudos for the reactivity!

Thanks
