### ISSUE TITLE
Feature v3_14 missing from manifest

### ISSUE THREAD

**Issue by brackleian** [gtk-rs/sourceview#92]
The doco for sourceview crate at `http://gtk-rs.org/docs/sourceview/struct.File.html` says I need feature `v3_14` to enable use of sourceview::File, so I changed my Cargo.toml `[dependencies]` from
`sourceview = "0.5.0"`
to
`sourceview = { version = "0.5.0", features = ["v3_14"] }`
and now get errors saying
`failed to select a version for 'sourceview'. ... required by package 'foo v0.1.0 (/projects/foo)' versions that meet the requirements '^0.5.0' are: 0.5.0 the package 'foo' depends on 'sourceview', with features: 'v3_14' but 'sourceview' does not have these features.`

The sourceview manifest is presumably missing a line like:
`v3_14 = ["v3_12", "gtk-source-sys/v3_14"]`

Is there a temporary work-around I can do for this?

**Comment by EPashkin** [comment]
Thanks for reporting this, it really missing.

**Comment by EPashkin** [comment]
As temporary solution you can clone "crate" branch locally, make changes and use it with [patch](https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section) in your project

**Comment by brackleian** [comment]
@EPashkin: thanks; tried your suggestion but it gives dependency problems:

`error: multiple packages link to native library 'cairo', but a native library can be linked only once`

`package 'cairo-sys-rs v0.6.0'`
`    ... which is depended on by 'gdk v0.8.0'`
`    ... which is depended on by 'gtk v0.4.1'`
`    ... which is depended on by 'foo v0.1.0 (.../foo)'`
`links to native library 'cairo'`

`package 'cairo-sys-rs v0.8.0 (https://github.com/gtk-rs/cairo#786e294e)'`
`    ... which is depended on by 'gtk-source-sys v0.8.0 (.../foo/sourceview/sourceview-sys)'`
`    ... which is depended on by 'sourceview v0.6.0 (.../foo/sourceview)'`
`    ... which is depended on by 'foo v0.1.0 (.../foo)'`
`also links to native library 'cairo'`

My project `foo` doesn't use cairo directly, so I don't know how to avoid this situation.

**Comment by EPashkin** [comment]
@brackleian Sorry, I missed that you use previous version of sourceview.
You needed use tag "0.5.0" instead  "crate" branch as fix base

**Comment by brackleian** [comment]
@EPashkin: thanks again; cloned --branch 0.5.0, then tried build; it came up with this:

`   Compiling sourceview v0.5.0 (.../foo/sourceview)`
`   Compiling gtk-source-sys v0.7.0`
`error[E0599]: no method named 'to_glib_none' found for type '&[&auto::encoding::Encoding]' in the current scope`
`   --> sourceview/src/auto/file_loader.rs:198:108`
`    |`
`198 |             ffi::gtk_source_file_loader_set_candidate_encodings(self.to_glib_none().0, candidate_encodings.to_glib_none().0);`
`    |                                                                                                            ^^^^^^^^^^^^`
`    |`
`    = note: the method 'to_glib_none' exists but the following trait bounds were not satisfied:`
`            '&[&auto::encoding::Encoding] : glib::translate::ToGlibPtr<_>'`
`            '[&auto::encoding::Encoding] : glib::translate::ToGlibPtr<_>'`

The error went away when I removed the `features = ["v3_14"]` from my Cargo.toml.  Could this be an actual error that has slipped past testing in v3_14?

**Comment by EPashkin** [comment]
This function not supported even after in last release,
so just remove it https://github.com/gtk-rs/sourceview/pull/93/files#diff-077aca5ddcbd0a679613d015c3d4a2e4

**Comment by brackleian** [comment]
@EPashkin: Yup, that fixed it. Many thanks for all your help.
