### ISSUE TITLE
A way to get text from Buffer of a sourceview.

### ISSUE THREAD

**Issue by ivanceras** [gtk-rs/sourceview#94]
I have a [sourceview::Buffer](https://gtk-rs.org/docs/sourceview/struct.Buffer.html) which is then used inside of a `soureview::View`. Getting the text inside the buffer seems impossible at the current version.  The [TextBufferExt](https://gtk-rs.org/docs/gtk/trait.TextBufferExt.html) is implemented by the sourceview::Buffer, with a [`get_text`](https://gtk-rs.org/docs/gtk/trait.TextBufferExt.html#tymethod.get_text) method. 
This is the signature of the method
```rust
fn get_text(
    &self,
    start: &TextIter,
    end: &TextIter,
    include_hidden_chars: bool
) -> Option<GString>
```
but it needs [TexIter](https://gtk-rs.org/docs/gtk/struct.TextIter.html) as argument, which can not be instantiated, nor derived from numbers or anything.

I just need to get all the text in the buffer starting from 0 to end.
This seems impossible to do it.

**Comment by ivanceras** [comment]
Nvm, found [this method](https://gtk-rs.org/docs/gtk/trait.TextBufferExt.html#tymethod.get_start_iter)
```rust
let text = buffer.get_text(&buffer.get_start_iter(), &buffer.get_end_iter(), false);
```
It's very unintuitive, but it does the job.

**Comment by matthiasdiener** [comment]
This is the same that you need to do for `TextView`, I believe.
